# [shell]
# program = "c:/scoop/apps/pwsh/current/pwsh.exe"

[general]
live_config_reload = false
# working_directory = "None"

import = [
 "~/.config/alacritty/breeze.toml"
]

[window]
dimensions = { columns = 160, lines = 40 }
padding = { x = 4, y = 4 }
resize_increments = true

[font]
size = 16
offset = { y=-2 }

[font.normal]
family = "ZedMono Nerd Font"

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
bindings = [
 { mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
 # { key = "C", mods = "Control", action = "Copy" },
 { key = "V", mods = "Control", action = "Paste" },
 { key = "PageUp", mods = "Shift", action = "ScrollHalfPageUp" },
 { key = "PageDown", mods = "Shift", action = "ScrollHalfPageDown" },
]

[selection]
save_to_clipboard = true

